export type TechID =
  | "EXTENDS_LAB"
  | "EXTENDS_FACTORY"
  | "EXTENDS_ROAD"
  | "FASHIONISTA"
  | "RESEARCH_LAB"
  | "RESEARCH_FACTORY"
  | "RESEARCH_ROAD"
  | "PET_LOVER"
  | "LUCKY_COIN"
  | "BROKEN_CLOCK"
  | "ADVANCED_BOARD"
  | "FOUR_LEAF_CLOVER"
  | "GRATE_CLAN";
